Смольников Максим
urfu-2017/autotests-task-02 pull request #18
Opened 2018-04-18 12:05 UTC by Rolyx2

2018-04-25 07:46 UTC, Zhigalov requested changes
В этой домашке нужно потренироваться писать интеграционные тесты. Нужно протестировать функцию showTweets подменив настоящие зависимости фейковыми.

2018-04-25 07:46 UTC, Zhigalov commented on lib/formatDate.js
> +module.exports = function formatDate (secondDay) {
Почему переменная называется "второй день"?
В функцию `formatDate` дата передается

2018-04-25 07:46 UTC, Zhigalov commented on tests/index-test.js
> +describe('Проверка даты', () => {
Проверку даты нужно делать в файле с названием `formatDate-test.js`
То есть добавлять суффикс `-test.js` к названию файла с кодом

2018-04-25 07:46 UTC, Zhigalov commented on tests/index-test.js
> +        }
Если использовать функцию [assert.throws](https://nodejs.org/api/assert.html#assert_assert_throws_block_error_message), то этот тест запишется компактнее.

2018-04-25 07:46 UTC, Zhigalov commented on tests/index-test.js
> +        { date: moment().subtract(1, 'day').utc().format(), expected: `вчера в ${moment().format('HH:mm')}` },
Лучше делать `expected` значение строкой, как в педыдущих тестах
Или зафиксировать текущее время. Чтобы не получилось так, что в актуальном значении время на миллисекунду раньше из-за чего тест будет иногда (при переходе через минуту) падать.

2018-04-25 16:58 UTC, Rolyx2 commented on tests/index-test.js
> +        }
Пробовал  через   assert.throws , локально тесты проходят, тут нет. 
{ date: '', expected: 'Not valid date' },
        { date: 'Дата', expected: 'Not valid date' },].forEach(({ date, expected }) =>
    it(`should throw error '${expected}' for '${date}'`, ()=> {
        assert.throws(() => formatDate(date), expected);
    }));
(вернул обратно try catch)

2018-05-06 15:49 UTC, Zhigalov reviewed
Нужны ещё доработки по этой домашке.

2018-05-06 15:49 UTC, Zhigalov commented on tests/formatDate-test.js
> +            formatDate(date);
Если `formatDate` не выбросит исключение, то тест пройдёт.
Это неправильно. В лекции я давал два варианта как можно отловить ошибку. Используй любой.

2018-05-06 15:49 UTC, Zhigalov commented on tests/formatDate-test.js
> +        { date: moment(today).subtract(1, 'month').format(), expected: `${moment(today).subtract(1, 'month').locale('ru').format('DD MMMM [в] HH:mm')}`},
Что будет, если запустить тест 5го января 2019 года?

2018-05-06 15:49 UTC, Zhigalov commented on tests/index-test.js
> +        assert.equal(print.callCount, 4);
Неплохо было бы проверить с какими аргументами вызвали `print`.
Чтобы это было удобнее делать, можешь заменить `getTweets` и `formatDate` на стабы с предопределённым поведением.

2018-05-14 08:22 UTC, Zhigalov commented on tests/formatDate-test.js
> +        { date : '2019-01-05T12:00:10.123Z', expected : /The entered date is in the future/},].forEach(({ date, expected }) =>
Тебе нужно зафиксировать время при помощи [sinon fake timers](http://sinonjs.org/releases/v1.17.7/fake-timers/)
Иначе 6 января 2019 года этот тест упадёт

2018-05-14 08:22 UTC, Zhigalov commented on tests/formatDate-test.js
> +        { date: moment(today).subtract(1, 'month').format(), expected: `${moment(today).subtract(1, 'month').locale('ru').format('DD MMMM [в] HH:mm')}`},
В этом комментарии я хотел сказать, что нужно писать такие тесты, чтобы они проходили в любое время.
Подменяй настоящее время на фэйковое

2018-05-14 08:22 UTC, Zhigalov commented on tests/index-test.js
> +});
Эти подмены выполнены правильно, молодец!

2018-05-16 10:48 UTC, Zhigalov approved these changes
Принято

2018-05-16 10:50 UTC, Zhigalov approved these changes

2018-05-16 10:50 UTC, closed without merging