Мишакова Наталья
urfu-2017/autotests-task-02 pull request #2
Opened 2018-04-16 16:35 UTC by mishakova

2018-04-21 15:44 UTC, mrprovoker requested changes
Есть одно критичное замечание. Тесты сегодня уже не будут запускаться. 

Давай решим эту проблему

2018-04-21 15:44 UTC, mrprovoker commented on lib/formatDate.js
> +
У меня есть общие замечания, которые относятся коду. Но так как у нас курс по тестированию я не буду требовать их исправление, а напишу просто советы по улучшению

2018-04-21 15:44 UTC, mrprovoker commented on lib/formatDate.js
> +
1. Переменные нужно объявлять через ключевые слова var/let/const
2. Старайся отделять логические операции пробелами, например ```parseInt(array[3]) > 24```
3. Старайся в любом случае действия в if/else выделять фигурными скобками, например
вместо: ```if (array[0]>dateNow.getUTCFullYear()) throw new Error('Future year');```
писать:
```
if (array[0] > dateNow.getUTCFullYear()) {
    throw new Error('Future year');
}
```

После этого твой код будет более читаемым 👍

2018-04-21 15:44 UTC, mrprovoker commented on lib/formatDate.js
> +	array = date.match(/\d+/g);
В рамках курса по тестированию некритично.

А такой способ парсинга был нарочно выбран?
Просто можно было написать: ``` var d = new Date(date); ``` А дальше у переменной вызывать методы getMonth, getYear и так далее.

2018-04-21 15:44 UTC, mrprovoker commented on lib/index.js
> +const print = require('./print');
гитхаб подчеркивает, что в коде есть лишние пробелы. Их лучше не добавлять

2018-04-21 15:44 UTC, mrprovoker commented on lib/index.js
> +	result += "Конец";
а зачем добавлять "Конец"? в задании такого не было

2018-04-21 15:44 UTC, mrprovoker commented on tests/index-test.js
> +    formatDate.withArgs('2018-04-15T15:09:10.609Z').returns('вчера в 15:09');
У тебя выше используется таб, а в этой строчке 4 пробела. Старайся использовать что-то одно, иначе будет выглядеть неровно.

2018-04-21 15:44 UTC, mrprovoker commented on tests/index-test.js
> +		const actual = formatDate(date); assert.equal(actual, expected);
лучше не писать несколько действий в одной строчке

2018-04-21 15:44 UTC, mrprovoker commented on tests/index-test.js
> +	var result = "вчера в 15:09 Библиотека #nock позволяет не только удобно писать тесты, но и вести разработку фронтеда, в то время, когда бекенд ещё только проектируется! #urfu-testing-2017 25 марта 2
у тебя сейчас твиты склеиваются. А должно выводиться с переводом строк
```
вчера в 15:09
Библиотека #nock позволяет не только удобно писать тесты, но и вести разработку фронтеда, в то время, когда бекенд ещё только проектируется! #urfu-testing-2017

25 декабря 2016 года в 12:00
Для подмены модулей раньше я использовал #mockery, а сейчас всей душой полюбил #proxyquire. #urfu-testing-2017
```

2018-04-21 15:44 UTC, mrprovoker commented on tests/index-test.js
> +	it('should print Only time for today', runSuccessTest('2018-04-16T15:09:10.609Z',"15:09"));
А если я сегодня (21 апреля) запущу эти тесты - они пройдут? кажется что нет

2018-04-23 13:54 UTC, mishakova commented on lib/formatDate.js
> +	array = date.match(/\d+/g);
Почему-то такое простое решение не пришло в голову

2018-04-23 14:23 UTC, mishakova commented
Исправила проблему с тестами, теперь они не зависят от текущей даты

2018-04-27 04:19 UTC, mrprovoker approved these changes
Молодец. Задание засчитано

2018-04-27 04:19 UTC, mrprovoker commented on tests/index-test.js
> +describe('formatDate', () => {
По хорошему эти тесты разнести на разные файлы:
showTweets-test.js 
formatDate-test.js

2018-04-27 04:19 UTC, closed without merging