Станислав Прошин
urfu-2017/autotests-task-02 pull request #3
Opened 2018-04-17 16:08 UTC by Orenheim

2018-05-08 09:35 UTC, zanevskaya requested changes
Тестовые кейсы правильные.

Из-за того что форматирование даты проверяется интеграционно, тесты выглядят громоздко. Протестируй форматирование даты модульно в файле `tests/formatDate-test.js`

2018-05-08 09:35 UTC, zanevskaya commented on tests/index-test.js
> +        assert.ok(print.calledWith('Тестировщик заходит в бар'));
Нудно проверить, что `print` вызвали только три раза

2018-05-08 09:35 UTC, zanevskaya commented on tests/index-test.js
> +    it('should format today tweets properly', () => {
Не нужно проверять `formatDate` через `showTweets`
Напиши модульные тесты на форматирование даты

2018-05-08 09:35 UTC, zanevskaya commented on tests/index-test.js
> +            text: 'Вневременной тестировщик всегда был в баре'
Прикольные тестовые сообщения! 👍

2018-05-09 13:49 UTC, Orenheim commented
Я вроде написал тесты отдельно, но я не знаю как сделать чтобы команда npm test их запускала. Она запускает только исходный файл и я не знаю как настроить связь между ними.

2018-05-14 10:45 UTC, zanevskaya commented
В travis все запускается. Если тебе что-то непонятно, подойти на лекции к Сергею Жигалову, он тебе подробней все расскажет. :)

2018-05-14 10:46 UTC, closed without merging